package com.lxhdj.dao.domain;

import java.util.Date;

public class ActivityPinDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_pin.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_pin.activity_id
     *
     * @mbggenerated
     */
    private Integer activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_pin.launch_task_pin
     *
     * @mbggenerated
     */
    private String launchTaskPin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_pin.activity_status
     *
     * @mbggenerated
     */
    private Integer activityStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_pin.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_pin.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_pin.id
     *
     * @return the value of activity_pin.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_pin.id
     *
     * @param id the value for activity_pin.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_pin.activity_id
     *
     * @return the value of activity_pin.activity_id
     *
     * @mbggenerated
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_pin.activity_id
     *
     * @param activityId the value for activity_pin.activity_id
     *
     * @mbggenerated
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_pin.launch_task_pin
     *
     * @return the value of activity_pin.launch_task_pin
     *
     * @mbggenerated
     */
    public String getLaunchTaskPin() {
        return launchTaskPin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_pin.launch_task_pin
     *
     * @param launchTaskPin the value for activity_pin.launch_task_pin
     *
     * @mbggenerated
     */
    public void setLaunchTaskPin(String launchTaskPin) {
        this.launchTaskPin = launchTaskPin == null ? null : launchTaskPin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_pin.activity_status
     *
     * @return the value of activity_pin.activity_status
     *
     * @mbggenerated
     */
    public Integer getActivityStatus() {
        return activityStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_pin.activity_status
     *
     * @param activityStatus the value for activity_pin.activity_status
     *
     * @mbggenerated
     */
    public void setActivityStatus(Integer activityStatus) {
        this.activityStatus = activityStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_pin.modify_time
     *
     * @return the value of activity_pin.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_pin.modify_time
     *
     * @param modifyTime the value for activity_pin.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_pin.create_time
     *
     * @return the value of activity_pin.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_pin.create_time
     *
     * @param createTime the value for activity_pin.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}